name: Deploy Jekyll

on:
  push:
    branches: [ development ]

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:

      - name: Make _site
        run: mkdir _site

      - name: checkout development
        uses: actions/checkout@v2
        with:
          path: _site

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          working-directory: _site
          bundler-cache: true

      - name: jekyll build
        run: cd _site && JEKYLL_ENV=production bundle exec jekyll build

      - name: push _site to master
        run: |
          cd _site
          cd _site
          git init
          git config user.name "Ed Gibbs"
          git config user.email "ed@edgibbs.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "jekyll build from Action ${GITHUB_RUN_NUMBER} :octocat:"
          git push --force origin master:master
